server:
  port: 8080

spring:
  data:
    redis:
      host: redis
      port: 6379
      timeout: 10s

  cloud:
    consul:
      host: consul
      port: 8500

    config:
      overrideSystemProperties: false
      overrideNone: true

  datasource:
    url: jdbc:postgresql://postgres:5432/nerabbs
    username: nerabbs
    password: nerabbs

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: always
      schema: "classpath:quartz-schema.sql"
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            classLoadHelper:
              class: org.quartz.simpl.CascadingClassLoadHelper
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  threads:
    virtual:
      enabled: true

sa-token:
  token-name: nerabbs

minio:
  endpoint: "http://minio:9000"
  user: nerabbs
  password: nerabbs#strong_password@2023

meilisearch:
  endpoint: "http://meilisearch:7700"
  masterKey: nerabbs#strong_password@2023

grpc:
  server:
    security:
      enabled: false
  client:
    nerabbs-service-user:
      address: "discovery:///nerabbs-service-user"
      negotiationType: PLAINTEXT
    nerabbs-service-webauthn:
      address: "discovery:///nerabbs-service-webauthn"
      negotiationType: PLAINTEXT
    nerabbs-service-post:
      address: "discovery:///nerabbs-service-post"
      negotiationType: PLAINTEXT
    nerabbs-service-search:
      address: "discovery:///nerabbs-service-search"
      negotiationType: PLAINTEXT
    nerabbs-service-comment:
      address: "discovery:///nerabbs-service-comment"
      negotiationType: PLAINTEXT
    nerabbs-service-user-profile:
      address: "discovery:///nerabbs-service-user-profile"
      negotiationType: PLAINTEXT
    nerabbs-service-oss:
      address: "discovery:///nerabbs-service-oss"
      negotiationType: PLAINTEXT

nerabbs:
  frontend:
    url: http://frontend:3000
  oss:
    upload:
      allowed-file-mime-types:
        - image/jpeg
        - image/png
        - image/gif
        - image/bmp
        - image/webp
        - image/avif
